AMPLICON_LIST="1 2 3"

# SN_HANDLE-rev - SN_HANDLE-fwd
SEQ_CS1_F_1="AGATCGGAAGAGCGTCGTGTAGGGATCCCTACACGACGCTCTTCCGATCT"
SEQ_EPF_F_1=""
SEQ_CS1_EPF_F_1="$SEQ_CS1_F_1""$SEQ_EPF_F_1"
SEQ_CS1_EPF_F_DEC_1=${SEQ_CS1_EPF_F_1:0:15}
SEQ_BPF_1="AGATCGGAAGAGCGTCGTGTAGGGATCCCTACACGACGCTCTTCCGATCT"
BRK_OFFSET_1=25

# SN_TSO-rev - SN_HANDLE-fwd
SEQ_CS1_F_2="CCCATGTACTCTGCGTTGATACCACTGCTTTCCCTACACGACGCTCTTCCGATCT"
SEQ_EPF_F_2=""
SEQ_CS1_EPF_F_2="$SEQ_CS1_F_2""$SEQ_EPF_F_2"
SEQ_CS1_EPF_F_DEC_2=${SEQ_CS1_EPF_F_2:0:15}
SEQ_BPF_2="CCCATGTACTCTGCGTTGATACCACTGCTTTCCCTACACGACGCTCTTCCGATCT"
BRK_OFFSET_2=30

# SN_TSO-rev - SN_TSO-fwd
SEQ_CS1_F_3="CCCATGTACTCTGCGTTGATACCACTGCTTAAGCAGTGGTATCAACGCAGAGTACATGGG"
SEQ_EPF_F_3=""
SEQ_CS1_EPF_F_3="$SEQ_CS1_F_3""$SEQ_EPF_F_3"
SEQ_CS1_EPF_F_DEC_3=${SEQ_CS1_EPF_F_3:0:15}
SEQ_BPF_3="CCCATGTACTCTGCGTTGATACCACTGCTTAAGCAGTGGTATCAACGCAGAGTACATGGG"
BRK_OFFSET_3=30

SKIP_DECODING="Y"
